### ISSUE TITLE
Taking too long

### ISSUE THREAD

**Issue by BukuBukuChagma** [Yariya/Zmap-ProxyScanner#3]
After installing everything when I run the .exe file it keeps running forever without saving anything in output.txt. Am I doing anything wrong.
The .exe has been running for atleast two hours now and heres the console logs:
![image](https://user-images.githubusercontent.com/101037978/209151523-d7151e94-8271-4238-931c-ef63b5e2ad5b.png)

**Comment by Yariya** [comment]
Hello, 

You have to use it with zmap.

example:
zmap -p 8080 | ./ZmapProxyScanner -p 8080 -o output.txt
